version: "3.9"

services:
  database:
    image: postgres
    container_name: devshop
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=devshop
    volumes: 
      - ./pgdata:/data/devshop
